name: draft-vtag-release-zip

on:
  workflow_dispatch: # Manual trigger.
  push:
    tags: ["v*"]

# Security: Restrict default permissions
permissions:
  actions: read    # Required for ci-checks workflow
  checks: write    # Required for ci-checks workflow
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  DOTNET_VERSION: '9.0.x'
  # Environment variables for release configuration
  CONFIGURATION: Release
  WPFAPP_CSPROJ_PATH: src/SampleWpfApp/SampleWpfApp.csproj
  TARGET_RUNTIME: win-x64

jobs:

  #ci-checks:
  #  name: CI Checks
  #  uses: ./.github/workflows/ci-checks.yml

  get-version-job:
    name: Get version from v-tag job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      has-vtag: ${{ steps.get-version.outputs.has-vtag }}
      release-version: ${{ steps.get-version.outputs.RELEASE_VERSION }}
    steps:
      - name: 🏷️ Get and check version from v-tag
        id: get-version
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match '^refs/tags/v') {
            $tagName = $env:GITHUB_REF -replace '^refs/tags/', ''
            $version = $tagName -replace '^v', ''
            Write-Host "Tag name: $tagName"
            Write-Host "Release version: $version"
            Write-Host "✅ Tag '$tagName' starts with 'v'"
            # Output as workflow step variables.
            "has-vtag=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            $tagName = $env:GITHUB_REF -replace '^refs/tags/', ''
            Write-Host "❌ Tag '$tagName' does not start with 'v'"
            Write-Host "GITHUB_REF: $env:GITHUB_REF"
            Write-Output "::warning title=Skipping Workflow::Tag is not a valid v-tag. ($env:GITHUB_REF)"
            # Output as workflow step variable.
            "has-vtag=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

  build-publish-wpf-app-artifact-job:
    name: Build and publish WPF app artifact
    needs: get-version-job
    if: needs.get-version-job.outputs.has-vtag == 'true'
    runs-on: windows-2022
    timeout-minutes: 20
    outputs:
      wpf-app-assembly-name: ${{ steps.get-assembly-name.outputs.WPF_APP_ASSEMBLY_NAME }}
    steps:

      - name: 🤘 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🔍 Extract AssemblyName from WPF app project
        id: get-assembly-name
        shell: pwsh
        run: |
          # Import the module
          Import-Module "./.github/workflows/pwsh/Get-AssemblyNameOrExit.psm1" -Force

          # Call the function and capture result
          $assemblyName = Get-AssemblyNameOrExit -ProjectPath $env:WPFAPP_CSPROJ_PATH

          Write-Host "Extracted WPF app exe name: $assemblyName"

          # Output as workflow step variable.
          "WPF_APP_ASSEMBLY_NAME=$assemblyName" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

          # WPF_APP_ASSEMBLY_NAME is the name of the WPF app executable's assembly without any file extension.

      - name: 📦 dotnet publish WPF app artifacts
        shell: pwsh
        run: |
          dotnet publish `
            $env:WPFAPP_CSPROJ_PATH `
            --configuration $env:CONFIGURATION `
            --self-contained `
            --runtime $env:TARGET_RUNTIME `
            --output ${{ runner.temp }}/artifact-output `
            --verbosity minimal

      - name: 📦 Create zip archive of WPF app
        shell: pwsh
        run: |
          $artifactPath = "${{ runner.temp }}/artifact-output"
          $zipPath = "${{ runner.temp }}/${{ steps.get-assembly-name.outputs.WPF_APP_ASSEMBLY_NAME }}.zip"
          Compress-Archive -Path "$artifactPath\*" -DestinationPath $zipPath -Force
          Write-Host "Created zip archive: $zipPath"

      - name: 🔒 Generate checksums (for zip file)
        shell: pwsh
        run: |
          $zipPath = "${{ runner.temp }}/${{ steps.get-assembly-name.outputs.WPF_APP_ASSEMBLY_NAME }}.zip"
          $externalChecksumsPath = "${{ runner.temp }}/checksums.txt"
          $hash = Get-FileHash -Path $zipPath -Algorithm SHA256
          "$($hash.Hash)  $(Split-Path $zipPath -Leaf)" | Out-File -FilePath $externalChecksumsPath -Encoding UTF8
          Write-Host "Generated checksums (for zip file):"
          Get-Content $externalChecksumsPath

      - name: 📤 Upload WPF app zip to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-assembly-name.outputs.WPF_APP_ASSEMBLY_NAME }}-zip
          path: ${{ runner.temp }}/${{ steps.get-assembly-name.outputs.WPF_APP_ASSEMBLY_NAME }}.zip
          retention-days: 7

      - name: 📤 Upload checksums to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: ${{ runner.temp }}/checksums.txt
          retention-days: 7

  draft-release-wpf-app-job:
    name: Create draft release for WPF app
    runs-on: ubuntu-latest
    needs: [get-version-job, build-publish-wpf-app-artifact-job]
    timeout-minutes: 10
    permissions:
      contents: write
    steps:

      - name: 🤘 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Needs full depth for generating release notes

      - name: 📥 Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-publish-wpf-app-artifact-job.outputs.wpf-app-assembly-name }}-zip
          path: ${{ runner.temp }}/dist

      - name: 📥 Download checksums artifact
        uses: actions/download-artifact@v4
        with:
          name: checksums
          path: ${{ runner.temp }}/dist

      - name: 📝 Generate release notes
        id: release-notes
        shell: pwsh
        run: |
          # Use the version extracted from the get-version-job
          $version = "${{ needs.get-version-job.outputs.release-version }}"

          $artifactZipName = "${{ needs.build-publish-wpf-app-artifact-job.outputs.wpf-app-assembly-name }}.zip"
          # Get the executable name from the extracted AssemblyName
          $appName = "${{ needs.build-publish-wpf-app-artifact-job.outputs.wpf-app-assembly-name }}"
          $exeName = "${{ needs.build-publish-wpf-app-artifact-job.outputs.wpf-app-assembly-name }}.exe"

          Write-Host "version: $version"
          Write-Host "artifactZipName: $artifactZipName"
          Write-Host "appName: $appName"
          Write-Host "exeName: $exeName"

          # Create release notes using StringBuilder for multiline content
          $sb = [System.Text.StringBuilder]::new()
          [void]$sb.AppendLine("## v$version $appName")
          [void]$sb.AppendLine("")
          [void]$sb.AppendLine("### What's New")
          [void]$sb.AppendLine("This release includes the latest features and improvements for $appName.")
          [void]$sb.AppendLine("")
          [void]$sb.AppendLine("### Download")
          [void]$sb.AppendLine("- **Windows (x64)**: Download the zip file from the assets below")
          [void]$sb.AppendLine("- **Checksums**: SHA256 checksums are provided for security:")
          [void]$sb.AppendLine("  - **checksums.txt**: Contains the checksum for the zip file itself")
          [void]$sb.AppendLine("")
          [void]$sb.AppendLine("### Verification")
          [void]$sb.AppendLine("1. Download both the zip file and checksums.txt")
          [void]$sb.AppendLine("2. Verify the zip file integrity: ``Get-FileHash $artifactZipName -Algorithm SHA256``")
          [void]$sb.AppendLine("3. Compare with the hash in checksums.txt")
          [void]$sb.AppendLine("")
          [void]$sb.AppendLine("### Installation")
          [void]$sb.AppendLine("1. Download and verify the zip file (see Verification above)")
          [void]$sb.AppendLine("2. Extract the zip file to your desired location")
          [void]$sb.AppendLine("3. Run ``$exeName`` to start the application")
          [void]$sb.AppendLine("")
          [void]$sb.AppendLine("### System Requirements")
          [void]$sb.AppendLine("- Windows 10 version 1809 or later")
          [void]$sb.AppendLine("- .NET 9.0 Runtime (included in self-contained build)")

          $sb.ToString() | Out-File -FilePath "release-notes.md" -Encoding utf8
          Write-Host "Generated release notes"

      - name: 🚀 Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release-notes: true
          fail_on_unmatched_files: true
          name: v${{ needs.get-version-job.outputs.release-version }} ${{ needs.build-publish-wpf-app-artifact-job.outputs.wpf-app-assembly-name }}
          tag_name: ${{ github.ref_name }}
          body_path: release-notes.md
          files: |
            ${{ runner.temp }}/dist/*
