name: draft-vtag-zip-release

on:
  workflow_dispatch: # Manual trigger.
  push:
    tags: ["v*"]
    # branches: ["rel-wrkflw-1"] # TODO: remove branches after testing.

# Security: Restrict default permissions
permissions:
  actions: read    # Required for ci-checks workflow
  checks: write    # Required for ci-checks workflow
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  DOTNET_VERSION: '9.0.x'
  # Environment variables for release configuration
  CONFIGURATION: Release
  WPFAPP_ARTIFACT_NAME: k0x-workbench-app
  WPFAPP_CSPROJ_PATH: src/SampleWpfApp/SampleWpfApp.csproj
  TARGET_RUNTIME: win-x64

jobs:

  #ci-checks:
  #  name: CI Checks
  #  uses: ./.github/workflows/ci-checks.yml

  build-publish-wpf-app-artifact:
    name: Build and publish WPF app artifact
    # needs: ci-checks
    runs-on: windows-2022
    timeout-minutes: 20
    steps:

      - name: 🤘 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 dotnet publish WPF app artifacts
        shell: pwsh
        run: |
          dotnet publish `
            $env:WPFAPP_CSPROJ_PATH `
            --configuration $env:CONFIGURATION `
            --self-contained `
            --runtime $env:TARGET_RUNTIME `
            --output ${{ runner.temp }}/artifact-output `
            --verbosity minimal

      - name: 🔒 Generate internal checksums (for files inside zip)
        shell: pwsh
        run: |
          $artifactPath = "${{ runner.temp }}/artifact-output"
          Get-ChildItem -Path $artifactPath -File -Recurse | ForEach-Object {
            $hash = Get-FileHash -Path $_.FullName -Algorithm SHA256
            "$($hash.Hash)  $($_.Name)" | Out-File -FilePath "$artifactPath/checksums.txt" -Append -Encoding UTF8
          }
          Write-Host "Generated internal checksums (included in zip):"
          Get-Content "$artifactPath/checksums.txt"

      - name: 📦 Create zip archive of WPF app
        shell: pwsh
        run: |
          $artifactPath = "${{ runner.temp }}/artifact-output"
          $zipPath = "${{ runner.temp }}/${{ env.WPFAPP_ARTIFACT_NAME }}.zip"
          Compress-Archive -Path "$artifactPath\*" -DestinationPath $zipPath -Force
          Write-Host "Created zip archive: $zipPath"

      - name: 🔒 Generate external checksums (for zip file)
        shell: pwsh
        run: |
          $zipPath = "${{ runner.temp }}/${{ env.WPFAPP_ARTIFACT_NAME }}.zip"
          $externalChecksumsPath = "${{ runner.temp }}/checksums.txt"
          $hash = Get-FileHash -Path $zipPath -Algorithm SHA256
          "$($hash.Hash)  $(Split-Path $zipPath -Leaf)" | Out-File -FilePath $externalChecksumsPath -Encoding UTF8
          Write-Host "Generated external checksums (for zip file):"
          Get-Content $externalChecksumsPath

      - name: 📤 Upload WPF app zip to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WPFAPP_ARTIFACT_NAME }}-zip
          path: ${{ runner.temp }}/${{ env.WPFAPP_ARTIFACT_NAME }}.zip
          retention-days: 7

      - name: 📤 Upload checksums to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: ${{ runner.temp }}/checksums.txt
          retention-days: 7

  draft-release-wpf-app:
    name: Create draft release for WPF app
    runs-on: ubuntu-latest
    needs: build-publish-wpf-app-artifact
    timeout-minutes: 10
    permissions:
      contents: write
    # TODO: Remove the branch part of the condition after testing
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/rel-wrkflw-1'
    steps:

      - name: 🤘 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Needs full depth for generating release notes

      - name: 📥 Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WPFAPP_ARTIFACT_NAME }}-zip
          path: ${{ runner.temp }}/dist

      - name: 📥 Download checksums artifact
        uses: actions/download-artifact@v4
        with:
          name: checksums
          path: ${{ runner.temp }}/dist

      - name: 🔍 Extract AssemblyName from WPF app project file
        id: extract_exe_name
        shell: bash
        run: |
          # Read AssemblyName from the project file
          ASSEMBLY_NAME=$(grep -oP '<AssemblyName>\K[^<]+' ${{ env.WPFAPP_CSPROJ_PATH }})
          echo "wpf_exe_name=$ASSEMBLY_NAME" >> $GITHUB_OUTPUT
          echo "Extracted WPF app exe name: $ASSEMBLY_NAME"

      - name: 📝 Generate release notes
        id: release_notes
        shell: bash
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          ARTIFACT_ZIP_NAME="${{ env.WPFAPP_ARTIFACT_NAME }}.zip"
          # Get the executable name from the extracted AssemblyName
          EXE_NAME="${{ steps.extract_exe_name.outputs.wpf_exe_name }}.exe"

          # Create release notes
          cat > release_notes.md << EOF
          ## K0x Workbench v$VERSION

          ### What's New
          This release includes the latest features and improvements for K0x Workbench.

          ### Download
          - **Windows (x64)**: Download the zip file from the assets below
          - **Checksums**: Two levels of SHA256 checksums are provided for security:
            - **checksums.txt**: Contains the checksum for the zip file itself
            - **Internal checksums**: The zip file contains a checksums.txt with hashes for all individual files

          ### Verification
          1. Download both the zip file and checksums.txt
          2. Verify the zip file integrity: \`Get-FileHash $ARTIFACT_ZIP_NAME -Algorithm SHA256\`
          3. Compare with the hash in checksums.txt
          4. After extraction, verify individual files using the checksums.txt inside the zip

          ### Installation
          1. Download and verify the zip file (see Verification above)
          2. Extract the zip file to your desired location
          3. Run $EXE_NAME to start the application

          ### System Requirements
          - Windows 10 version 1809 or later
          - .NET 9.0 Runtime (included in self-contained build)
          EOF

          echo "Generated release notes"

      - name: 🚀 Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          name: ${{ steps.extract_exe_name.outputs.wpf_exe_name }} v${{ steps.release_notes.outputs.version }}
          tag_name: ${{ github.ref_name }}
          body_path: release_notes.md
          files: |
            ${{ runner.temp }}/dist/*
